# Netlify build configuration for a Next.js project

[build]
  # Command to build the Next.js application
  command = "npm run build"
  
  # Explicitly set the publish directory for Next.js builds
  publish = ".next"
  
  # Directory containing serverless functions (API routes)
  # Netlify's Next.js runtime automatically detects functions in pages/api.
  functions = "src/pages/api"

[dev]
  # Optional: Settings for local development using Netlify Dev CLI
  # command = "npm run dev" # Command to start your dev server
  # port = 3000             # Port your dev server runs on
  # publish = ".next"       # Dev server build directory (if applicable)

# Plugin for essential Next.js features on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configure paths for functions
[functions]
  # Next.js API routes are stored in src/pages/api, but Netlify expects them in netlify/functions
  node_bundler = "esbuild"
  included_files = ["src/pages/api/**/*"]

# Configure generate-docs as a background function
[functions.generate-docs]
  background = true
  timeout = 900
  memory = 1024
  maxDuration = 900

# Environment variables configuration
[build.environment]
  # Set Netlify Blobs context - This variable is automatically set by Netlify but defining it here ensures it's available
  NETLIFY_BLOBS_CONTEXT = "production"
  # Node version
  NODE_VERSION = "18"

# Edge Function configuration for Open Graph image generation
[[edge_functions]]
  function = "og"
  path = "/api/og"

# Fallback rules for OG images if Edge Function fails
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
