# Netlify build configuration for a Next.js project

[build]
  # Command to build the Next.js application
  command = "npm run build"
  
  # Explicitly set the publish directory for Next.js builds
  publish = ".next"
  
  # Directory containing serverless functions (API routes)
  # Netlify's Next.js runtime automatically detects functions in pages/api.
  # functions = "netlify/functions" # Typically not needed for Next.js API routes

[dev]
  # Optional: Settings for local development using Netlify Dev CLI
  # command = "npm run dev" # Command to start your dev server
  # port = 3000             # Port your dev server runs on
  # publish = ".next"       # Dev server build directory (if applicable)

# Plugin for essential Next.js features on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configure paths for functions
[functions]
  # Next.js API routes are stored in src/pages/api, but Netlify expects them in netlify/functions
  directory = "src/pages/api"
  node_bundler = "esbuild"
  # Note: Node.js version is set via environment variable in Netlify UI

# Configure generate-docs as a background function
[functions."generate-docs"]
  node_bundler = "esbuild"
  background = true
  timeout = "900" # 15 minutes for background functions
  memory = 1024 # 1GB memory
  included_files = ["!node_modules/**/*"] # Exclude node_modules to reduce bundle size

# Environment variables configuration
[build.environment]
  # Set Netlify Blobs context - This variable is automatically set by Netlify but defining it here ensures it's available
  NETLIFY_BLOBS_CONTEXT = "production"
  # Node version
  NODE_VERSION = "18"

# Edge Function configuration for Open Graph image generation
[[edge_functions]]
  function = "og"
  path = "/api/og"

# Fallback rules for OG images if Edge Function fails
[[redirects]]
  from = "/api/og-fallback"
  to = "/cookfast-og-fallback.png"
  status = 200
  force = true
