# Netlify build configuration for a Next.js project

[build]
  # Command to build the Next.js application
  command = "npm run build"
  
  # Explicitly set the publish directory for Next.js builds
  publish = ".next"
  
  # Directory containing serverless functions (API routes)
  # Netlify's Next.js runtime automatically detects functions in pages/api.
  # functions = "netlify/functions" # Typically not needed for Next.js API routes

[dev]
  # Optional: Settings for local development using Netlify Dev CLI
  # command = "npm run dev" # Command to start your dev server
  # port = 3000             # Port your dev server runs on
  # publish = ".next"       # Dev server build directory (if applicable)

# Plugin for essential Next.js features on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configure paths for functions
[functions]
  # Next.js API routes are stored in src/pages/api, but Netlify expects them in netlify/functions
  directory = "src/pages/api"
  node_bundler = "esbuild"
  # Use Node.js 18.x to support all modern JavaScript features
  node_version = "18.x"

# Configure background functions for API calls that may take longer than 10 seconds
[functions."generate-docs"]
  node_bundler = "esbuild"
  node_version = "18.x"
  background = true

[functions."generate-docs-background"]
  node_bundler = "esbuild"
  node_version = "18.x"
  background = true

# Edge Function configuration for Open Graph image generation
[[edge_functions]]
  function = "og"
  path = "/api/og"

# Fallback rules for OG images if Edge Function fails
[[redirects]]
  from = "/api/og-fallback"
  to = "/cookfast-og-fallback.png"
  status = 200
  force = true
