// Generated by AI Assistant - Add MainLayout component
// Path: src/components/layout/MainLayout.tsx
import React from 'react';
import Header from './Header';
import EnhancedFooter from '@/components/EnhancedFooter';

interface MainLayoutProps {
  children: React.ReactNode;
}

const MainLayout: React.FC<MainLayoutProps> = ({ children }) => {
  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      <main className="flex-grow">
        {children}
      </main>
      <EnhancedFooter />
    </div>
  );
};

export default MainLayout; 